In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(list(uploaded.values())[0]))

print("\nEksik Değer Kontrolü:")
print(df.isnull().sum())

np.random.seed(42)
df["Na_to_K"] = df["Na_to_K"] + np.random.normal(0, 1.5, size=len(df))


df_encoded = pd.get_dummies(df, columns=["Sex", "BP", "Cholesterol"], drop_first=True)

X = df_encoded.drop("Drug", axis=1)
y = df_encoded["Drug"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train_scaled, y_train)
y_pred_svm = svm_model.predict(X_test_scaled)

print("\n=== SVM ===")
print("Test Accuracy:", accuracy_score(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

cv_scores_svm = cross_val_score(svm_model, X_train_scaled, y_train, cv=5)
print("Cross-Validation Ortalama Accuracy (SVM):", cv_scores_svm.mean())

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred_rf = rf_model.predict(X_test)

print("\n=== Random Forest ===")
print("Test Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

cv_scores_rf = cross_val_score(rf_model, X_train, y_train, cv=5)
print("Cross-Validation Ortalama Accuracy (Random Forest):", cv_scores_rf.mean())

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)

print("\n=== Naive Bayes ===")
print("Test Accuracy:", accuracy_score(y_test, y_pred_nb))
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

cv_scores_nb = cross_val_score(nb_model, X_train, y_train, cv=5)
print("Cross-Validation Ortalama Accuracy (Naive Bayes):", cv_scores_nb.mean())



Saving drug200.csv to drug200 (4).csv
Veri Seti İlk 5 Satır:
   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

Eksik Değer Kontrolü:
Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

=== SVM ===
Test Accuracy: 0.95
[[15  0  0  0  0]
 [ 1  5  0  0  0]
 [ 0  0  3  0  0]
 [ 1  0  0  4  0]
 [ 0  0  0  0 11]]
              precision    recall  f1-score   support

       DrugY       0.88      1.00      0.94        15
       drugA       1.00      0.83      0.91         6
       drugB       1.00      1.00      1.00         3
       drugC       1.00      0.80      0.89         5
       drugX       1.00      1.00      1.00        11

    accuracy                           0.95        40
   macro avg   